### ISSUE TITLE
Passing data fragment to fragment

### ISSUE THREAD

**Issue by adityajangle** [CodeKul/android-5-6-daily#1]
Kindly provide a sample for passing data fragment to Fragment in the same activity using our last demo

**Comment by aniruddhha** [comment]
**Inter fragment Communication**

[https://github.com/CodeKul/android-5-6-daily/blob/master/fragments/src/main/java/com/example/fragments/FooterFragment.kt](https://github.com/CodeKul/android-5-6-daily/blob/master/fragments/src/main/java/com/example/fragments/FooterFragment.kt)
