### ISSUE TITLE
frag.arguments = bn

### ISSUE THREAD

**Issue by adityajangle** [CodeKul/android-5-6-daily#3]
kindly explain the following line the need of **arguments**

**Comment by aniruddhha** [comment]
`public void setArguments(@Nullable Bundle args) {
        if (this.mIndex >= 0 && this.isStateSaved()) {
            throw new IllegalStateException("Fragment already active and state has been saved");
        } else {
            this.mArguments = args;
        }
    }`

As we discussed in todays and last lecture of fragment, fragment creates instance using java reflection api, which uses default constructor for object creation so fragment has given you argument(of type bundle) for data transportation.  check this [link](https://stackoverflow.com/questions/9245408/best-practice-for-instantiating-a-new-android-fragment)
