### ISSUE TITLE
Project Does Not open.

### ISSUE THREAD

**Issue by shubhamdixit1995** [CodeKul/android-5-6-daily#5]
The path
'D:\new envirement\android-sdk-windows'
does not belong to a directory.

Android Studio will use this Android SDK instead:
'C:\Users\cool\AppData\Local\Android\Sdk'
and will modify the project's local.properties file.[photo](https://drive.google.com/open?id=1F7F8VT70OTlrerCJfIr6JiUSu-OmXisu)

**Comment by aniruddhha** [comment]
Configuration Issue : Kindly create new project.
